In [1]:
import pandas as pd
import zipfile

In [2]:

# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials_1 = {
    'IAM_SERVICE_ID': 'iam-ServiceId-2d2af674-7712-4092-92aa-a650bf151038',
    'IBM_API_KEY_ID': 'AZQuiuKInh2JWwu4iseyHXr-yPS2k1UBMLntPZ1qSAsA',
    'ENDPOINT': 'https://s3.eu-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.cloud.ibm.com/oidc/token',
    'BUCKET': 'task5-donotdelete-pr-lsbc7bdrsduhsh',
    'FILE': 'Police_Department_Incidents_-_Previous_Year__2016_.zip'
}

In [3]:
#2.	Download the file into IBM Cloud Object Storage
from ibm_botocore.client import Config
import ibm_boto3

cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials_1['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials_1['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials_1['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials_1['ENDPOINT'])

In [4]:
cos.download_file(Bucket=credentials_1['BUCKET'],Key='Police_Department_Incidents_-_Previous_Year__2016_.zip',Filename='Police_Department_Incidents_-_Previous_Year__2016_.zip')

In [5]:
from zipfile import ZipFile
 
 
print('Extract all files in ZIP to current directory')
# Create a ZipFile Object and load in it
with ZipFile('Police_Department_Incidents_-_Previous_Year__2016_.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

Extract all files in ZIP to current directory

In [23]:
import pandas as pd
df = pd.read_csv('Police_Department_Incidents_-_Previous_Year__2016_.csv')
df

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150495,161061000,ASSAULT,BATTERY,Friday,12/30/2016 12:00:00 AM,21:01,PARK,NONE,OAK ST / STANYAN ST,-122.453982,37.771428,"(37.7714278595913, -122.453981622365)",16106100004134
150496,176000742,NON-CRIMINAL,LOST PROPERTY,Friday,12/30/2016 12:00:00 AM,08:00,CENTRAL,NONE,JACKSON ST / SANSOME ST,-122.401857,37.796626,"(37.7966261239618, -122.401857374739)",17600074271000
150497,176000758,LARCENY/THEFT,PETTY THEFT OF PROPERTY,Thursday,12/29/2016 12:00:00 AM,20:00,CENTRAL,NONE,PINE ST / TAYLOR ST,-122.412269,37.790673,"(37.7906727649886, -122.41226909106)",17600075806372
150498,176000764,LARCENY/THEFT,GRAND THEFT OF PROPERTY,Friday,12/30/2016 12:00:00 AM,10:00,CENTRAL,NONE,200 Block of STOCKTON ST,-122.406659,37.788275,"(37.7882745285785, -122.406658711008)",17600076406374
150499,179002868,OTHER OFFENSES,"FRAUDULENT GAME OR TRICK, OBTAINING MONEY OR P...",Friday,12/02/2016 12:00:00 AM,14:00,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",17900286809024

In [7]:
df.rename(columns={'PdDistrict':'Neighbourhood'}, inplace=True)
df.head()
df_1 = df['Neighbourhood'].value_counts()

       Category Neighbourhood
0   WEAPON LAWS      SOUTHERN
1   WEAPON LAWS      SOUTHERN
2      WARRANTS       BAYVIEW
3  NON-CRIMINAL    TENDERLOIN
4  NON-CRIMINAL       MISSION

In [16]:
df_n = pd.DataFrame({"Neighbourhood":['CENTRAL','NORTHERN','PARK','SOUTHERN','MISSION','TENDERLOIN','RICHMOND','TARAVAL','INGLESIDE','BAYVIEW'], 
                 "Count":[17666,20100,8699,28445,19503,9942,8922,11325,11594,14303]}) 
df_n

  Neighbourhood  Count
0       CENTRAL  17666
1      NORTHERN  20100
2          PARK   8699
3      SOUTHERN  28445
4       MISSION  19503
5    TENDERLOIN   9942
6      RICHMOND   8922
7       TARAVAL  11325
8     INGLESIDE  11594
9       BAYVIEW  14303

In [17]:
!wget --quiet https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/san-francisco.geojson

In [24]:
df_n = pd.DataFrame({"Neighbourhood":['CENTRAL','NORTHERN','PARK','SOUTHERN','MISSION','TENDERLOIN','RICHMOND','TARAVAL','INGLESIDE','BAYVIEW'], 
                 "Count":[17666,20100,8699,28445,19503,9942,8922,11325,11594,14303]}) 
df_n

# for sake of consistency, let's also make all column labels of type string
df_n.columns = list(map(str, df_n.columns))

# add total column
df_n['Count'] = df_n.sum(axis=1)
!wget --quiet https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/san-francisco.geojson
import folium
sanfran_geo = r'san-francisco.geojson' # geojson file
latitude = 37.77
longitude = -122.42

# create a numpy array of length 6 and has linear spacing from the minium total immigration to the maximum total immigration
threshold_scale = np.linspace(df_n['Count'].min(),
                              df_n['Count'].max(),
                              6, dtype=int)
threshold_scale = threshold_scale.tolist() # change the numpy array to a list
threshold_scale[-1] = threshold_scale[-1] + 1 # make sure that the last value of the list is greater than the maximum immigration

# create a plain world map
world_map = folium.Map(location=[latitude, longitude], zoom_start=12)
world_map.choropleth(
    geo_data=sanfran_geo,
    data=df_n,
    columns=['Neighbourhood', 'Count'],
    key_on='feature.properties.DISTRICT',
    threshold_scale = threshold_scale,
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    line_opacity=0.2,
    legend_name='Crime rate in Sanfransico',
    reset=True
)

# display map
world_map

ModuleNotFoundError: No module named 'folium'